language: objective-c
install: ''
before_script: ./Scripts/addkey.sh
script: ./build.sh
git:
  depth: 1
env:
  global:
  - secure: BIthbR5ZAiPMoajy4C10WJwabbR2uWxFzHCL6pyAqLNFI3gaOUw7BV2yiKi5Pd7IIl/Lg6Nn54j6XcqKyhkHmMkU4He+01Q1Afk90BhvglP439m7NVtp+KcKtZRIesdRfFuLsEkiOBZBAHXCNPhjMY3PE/HYK5cBE5aFmIPsD74=
  - secure: NpRsNEh2rYQzJRC3Slw0t4SBYAhrxNbUVx1yEKBTSBvXP8I0wUveaqt9PBXXE7zeTFsU1y9N5YCfFu/whETb7c8HDhiF8phHYqEPj6DMYYfSl5JjKiD4/C4xTPA6GQt5CjwIL+nm+LVTlhfyZdWu3Wn+HMU0LakLS1XEE53AU68=
  - CODE_SIGN_IDENTITY="iPhone Distribution: Appstax Technologies AS (L8V2M7RADW)"
  - PROFILE_NAME="Travis_Ad_Hoc_Distribution_Profile"
