language: objective-c
osx_image: xcode7
install: ''
before_script: 
  - ./Scripts/addkey.sh
  - brew update
  - brew install carthage
  - carthage bootstrap --verbose
script: ./build.sh
git:
  depth: 1
env:
  global:
  - CODE_SIGN_IDENTITY="iPhone Distribution: Appstax Technologies AS (L8V2M7RADW)"
  - PROFILE_NAME="Travis_Ad_Hoc_Distribution_Profile"
  - secure: ZHMwCd9X1c5c3fzB5QlNRqvj7TA6TobGspECBWhiG1huKMH0n0yJpwb5EeUC+iHJzXY32Fgx6080muUT8V4eyxY8lx0vepf7S4MGjd1y7iKjvL3lWicd1IWn6g1S+w9EiGd0mV2g8djAvP7yF+LIRa2NevIuodd7YxwiLPp3P/g=
  - secure: wfAQgOJ8ylQFKoJ1VY6BqmUYXjZFtqP1wDufENN0RcPjdfHoRdr5Or8Xlmn4H1uFhk4KvyVa3ik3gr/C0LOtXRF1ebdVCR6FUQDw0BffXMhjC/y8ITtzYaOe9Dsi8voYrzfMRSS4+LCcKIjwN3ETCappNBnHaXteJBb60YyzSMk=
deploy:
- provider: releases
  api_key:
    secure: z3NEF86jqUkyPXlsLVDmEodysR25zr594f8e+H96zgFES64VcjeKbItpu4OCoCVJCrq3Km8Cm5sdpT8jImkMkr+f8xVNUfHBiziy/xRKrLBUYlJN/A+rTwYAo9fSy8xJ3yUxa53irz20qHsQ9PNzn9ETpkBiUWU+2Gt9FPFWLqo=
  skip_cleanup: true
  file: Build/appstax-ios.zip
  on:
    tags: true
