language: objective-c
install: ''
before_script: ./Scripts/addkey.sh
script: ./build.sh
git:
  depth: 1
env:
  global:
  - secure: CMIkvacdAxHwNi16VKK8p5Bc8OJuFGZ/fFwrrpwzHKgUtVTsEQPlnsCo4R6CloWnmyEJYRs/UmlGwPJbRXS0sI50srk4kX3LUPkTaRkAFsOLpyZs1kpYy6YNm/V8j7F+p5iOvuDkzkOSD3QTMzM7Y0V8bTVqOZLFU8R0nizZgSY=
  - secure: rfhzlf6vFWa8X3BGaHumE+w6LYebNffWwkN6UBdQY4p1K/VbRoVaEMwAUh1pUysjmJW1Ch0DGjFshj8oS0PiYtm4DkPRollXSH53FnhtMb5R5q8HYTEoN4C1ZeN73bBnySwviwit2zWLEFFq21qa/PaJpeKHSVAEuahB4hS69hQ=
  - CODE_SIGN_IDENTITY="iPhone Distribution: Appstax Technologies AS (L8V2M7RADW)"
  - PROFILE_NAME="Travis_Ad_Hoc_Distribution_Profile"
deploy:
- provider: releases
  api_key:
    secure: jUE2mYhPRhTQ87cDcSXIiI1ncoqTq1vNeKJBqb8wbpkYE6Fmp5S7/nBV+iXNwyoV9Ls3LvvEz6FLjecX7UI2eVrLtjLGZhro9HqCBKoWDX7H6usLR6WBFeycY+0xFTTMRTTE/0LfTpOrZrbs03wyt8WhlyvKHoSBpjN6UPBEDvs=
  skip_cleanup: true
  file: Build/appstax-ios.zip
  on:
    tags: true
